# site settings
title: Neil Shah
subtitle:
email: neilshah55@gmail.com
description: A site to tell you a little bit more about me<br /> and reach out to me if you have any ideas.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Neil Shah
country: Singapore
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/neilshah13
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/neil-shah-/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
